-- migrate:up

COMMENT ON SCHEMA public IS 'standard public schema';

--
-- Invite
--

CREATE TABLE public."Invite" (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    room bigint NOT NULL,
    invited_by integer,
    token uuid DEFAULT gen_random_uuid() NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "Invite_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'expired'::text])))
);

COMMENT ON TABLE public."Invite" IS 'invtites ,  room admins used to add a new friend';

ALTER TABLE public."Invite" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Invite_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Users
--

CREATE TABLE public."Users" (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    uid character varying,
    email character varying DEFAULT ''::character varying NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    profile text
);

COMMENT ON TABLE public."Users" IS 'all the members are using the app';
COMMENT ON COLUMN public."Users".profile IS 'This will be the profile picture of the user';

ALTER TABLE public."Users" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Members_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Rooms
--

CREATE TABLE public."Rooms" (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    uid character varying,
    name text
);

COMMENT ON TABLE public."Rooms" IS 'all the room uses the app';

ALTER TABLE public."Rooms" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Rooms_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- SpendingParticipants
--

CREATE TABLE public."SpendingParticipants" (
    id integer NOT NULL,
    spending_id integer NOT NULL,
    user_id integer NOT NULL
);

CREATE SEQUENCE public."SpendingParticipants_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public."SpendingParticipants_id_seq" OWNED BY public."SpendingParticipants".id;

--
-- Spendings
--

CREATE TABLE public."Spendings" (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    "user" text NOT NULL,
    money bigint NOT NULL,
    material text NOT NULL,
    room bigint NOT NULL,
    settled boolean
);

COMMENT ON TABLE public."Spendings" IS 'spendings table how members spends their budget';

ALTER TABLE public."Spendings" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Spendings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- UserRooms
--

CREATE TABLE public."UserRooms" (
    id integer NOT NULL,
    user_id integer NOT NULL,
    room_id integer NOT NULL,
    role text DEFAULT 'Member'::text NOT NULL,
    joined_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE SEQUENCE public."UserRooms_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public."UserRooms_id_seq" OWNED BY public."UserRooms".id;

--
-- balance
--

CREATE TABLE public.balance (
    id integer NOT NULL,
    room bigint NOT NULL,
    "user" character varying,
    amount double precision,
    status text,
    created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    spending_id integer
);

CREATE SEQUENCE public.balance_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.balance_id_seq OWNED BY public.balance.id;

--
-- notifications
--

CREATE TABLE public.notifications (
    id integer NOT NULL,
    room_id integer NOT NULL,
    triggered_by integer,
    activity_type character varying(50) NOT NULL,
    title character varying(255) NOT NULL,
    message text NOT NULL,
    data jsonb,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT check_activity_type CHECK (((activity_type)::text = ANY ((ARRAY['payment'::character varying, 'grocery'::character varying, 'expense'::character varying, 'member_join'::character varying, 'member_leave'::character varying])::text[])))
);

CREATE SEQUENCE public.notifications_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.notifications_id_seq OWNED BY public.notifications.id;

--
-- push_subscriptions
--

CREATE TABLE public.push_subscriptions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    room_id integer NOT NULL,
    endpoint text NOT NULL,
    p256dh_key text NOT NULL,
    auth_key text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE SEQUENCE public.push_subscriptions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.push_subscriptions_id_seq OWNED BY public.push_subscriptions.id;

--
-- Column defaults
--

ALTER TABLE ONLY public."SpendingParticipants" ALTER COLUMN id SET DEFAULT nextval('public."SpendingParticipants_id_seq"'::regclass);
ALTER TABLE ONLY public."UserRooms" ALTER COLUMN id SET DEFAULT nextval('public."UserRooms_id_seq"'::regclass);
ALTER TABLE ONLY public.balance ALTER COLUMN id SET DEFAULT nextval('public.balance_id_seq'::regclass);
ALTER TABLE ONLY public.notifications ALTER COLUMN id SET DEFAULT nextval('public.notifications_id_seq'::regclass);
ALTER TABLE ONLY public.push_subscriptions ALTER COLUMN id SET DEFAULT nextval('public.push_subscriptions_id_seq'::regclass);

--
-- Primary keys / unique constraints
--

ALTER TABLE ONLY public."Invite" ADD CONSTRAINT "Invite_token_key" UNIQUE (token);
ALTER TABLE ONLY public."Users" ADD CONSTRAINT "Members_id_key" UNIQUE (id);
ALTER TABLE ONLY public."Rooms" ADD CONSTRAINT "Rooms_id_key" UNIQUE (id);
ALTER TABLE ONLY public."Rooms" ADD CONSTRAINT "Rooms_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."SpendingParticipants" ADD CONSTRAINT "SpendingParticipants_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."SpendingParticipants" ADD CONSTRAINT "SpendingParticipants_spending_id_user_id_key" UNIQUE (spending_id, user_id);
ALTER TABLE ONLY public."Spendings" ADD CONSTRAINT "Spendings_id_key" UNIQUE (id);
ALTER TABLE ONLY public."Spendings" ADD CONSTRAINT "Spendings_pkey" PRIMARY KEY (id, created_at, money, material, room);
ALTER TABLE ONLY public."UserRooms" ADD CONSTRAINT "UserRooms_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."Users" ADD CONSTRAINT "Users_email_key" UNIQUE (email);
ALTER TABLE ONLY public."Users" ADD CONSTRAINT "Users_pkey" PRIMARY KEY (id, created_at);
ALTER TABLE ONLY public."Users" ADD CONSTRAINT "Users_profile_key" UNIQUE (profile);
ALTER TABLE ONLY public."Users" ADD CONSTRAINT "Users_uid_key" UNIQUE (uid);
ALTER TABLE ONLY public.balance ADD CONSTRAINT balance_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.push_subscriptions ADD CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.push_subscriptions ADD CONSTRAINT unique_user_room_subscription UNIQUE (user_id, room_id);
ALTER TABLE ONLY public."UserRooms" ADD CONSTRAINT uq_user_room UNIQUE (user_id, room_id);

--
-- Indexes
--

CREATE INDEX "Spendings_created_at_user_room_idx" ON public."Spendings" USING btree (created_at, "user", room);
CREATE INDEX idx_notifications_activity_type ON public.notifications USING btree (activity_type);
CREATE INDEX idx_notifications_created_at ON public.notifications USING btree (created_at DESC);
CREATE INDEX idx_notifications_room_id ON public.notifications USING btree (room_id);
CREATE INDEX idx_push_subscriptions_room_id ON public.push_subscriptions USING btree (room_id);
CREATE INDEX idx_push_subscriptions_user_id ON public.push_subscriptions USING btree (user_id);
CREATE INDEX idx_sp_spending_id ON public."SpendingParticipants" USING btree (spending_id);
CREATE INDEX idx_sp_user_id ON public."SpendingParticipants" USING btree (user_id);
CREATE INDEX idx_spendings_settled_room ON public."Spendings" USING btree (room, settled);
CREATE INDEX idx_userrooms_room_id ON public."UserRooms" USING btree (room_id);
CREATE INDEX idx_userrooms_user_id ON public."UserRooms" USING btree (user_id);
CREATE UNIQUE INDEX invite_token_idx ON public."Invite" USING btree (token);

--
-- Foreign keys
--

ALTER TABLE ONLY public."Invite" ADD CONSTRAINT "Invite_invited_by_fkey" FOREIGN KEY (invited_by) REFERENCES public."Users"(id);
ALTER TABLE ONLY public."Invite" ADD CONSTRAINT "Invite_room_fkey" FOREIGN KEY (room) REFERENCES public."Rooms"(id);
ALTER TABLE ONLY public."SpendingParticipants" ADD CONSTRAINT "SpendingParticipants_spending_id_fkey" FOREIGN KEY (spending_id) REFERENCES public."Spendings"(id) ON DELETE CASCADE;
ALTER TABLE ONLY public."SpendingParticipants" ADD CONSTRAINT "SpendingParticipants_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."Users"(id) ON DELETE CASCADE;
ALTER TABLE ONLY public."Spendings" ADD CONSTRAINT "Spendings_room_fkey" FOREIGN KEY (room) REFERENCES public."Rooms"(id);
ALTER TABLE ONLY public."Spendings" ADD CONSTRAINT "Spendings_user_fkey" FOREIGN KEY ("user") REFERENCES public."Users"(email);
ALTER TABLE ONLY public."UserRooms" ADD CONSTRAINT "UserRooms_room_id_fkey" FOREIGN KEY (room_id) REFERENCES public."Rooms"(id) ON DELETE CASCADE;
ALTER TABLE ONLY public."UserRooms" ADD CONSTRAINT "UserRooms_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."Users"(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.balance ADD CONSTRAINT balance_room_fkey FOREIGN KEY (room) REFERENCES public."Rooms"(id);
ALTER TABLE ONLY public.balance ADD CONSTRAINT balance_spending_id_fkey FOREIGN KEY (spending_id) REFERENCES public."Spendings"(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.balance ADD CONSTRAINT balance_user_fkey FOREIGN KEY ("user") REFERENCES public."Users"(email);
ALTER TABLE ONLY public.notifications ADD CONSTRAINT fk_notifications_room FOREIGN KEY (room_id) REFERENCES public."Rooms"(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.notifications ADD CONSTRAINT fk_notifications_user FOREIGN KEY (triggered_by) REFERENCES public."Users"(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.push_subscriptions ADD CONSTRAINT fk_push_subscriptions_room FOREIGN KEY (room_id) REFERENCES public."Rooms"(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.push_subscriptions ADD CONSTRAINT fk_push_subscriptions_user FOREIGN KEY (user_id) REFERENCES public."Users"(id) ON DELETE CASCADE;

-- Note: Supabase-specific RLS policies (CREATE POLICY / ENABLE ROW LEVEL SECURITY / GRANT
-- to authenticated/anon/service_role) are intentionally excluded from this migration.
-- They're a Supabase platform security feature tied to Supabase-managed roles, not part of
-- this app's own schema, and don't apply to a plain local Postgres test database.

-- migrate:down

DROP TABLE IF EXISTS public.push_subscriptions CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.balance CASCADE;
DROP TABLE IF EXISTS public."SpendingParticipants" CASCADE;
DROP TABLE IF EXISTS public."UserRooms" CASCADE;
DROP TABLE IF EXISTS public."Spendings" CASCADE;
DROP TABLE IF EXISTS public."Invite" CASCADE;
DROP TABLE IF EXISTS public."Rooms" CASCADE;
DROP TABLE IF EXISTS public."Users" CASCADE;
