-- migrate:up

-- New domain: precomputed per-participant expense splits, and a fast-read
-- balance ledger replacing the dropped `balance` table. See docs/DOMAIN.md
-- (SpendingSplits / RoomBalanceSummary) and docs/TODOS.md Phase 0/1.

CREATE TABLE public."SpendingSplits" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spending_id bigint NOT NULL,
    user_id bigint NOT NULL,
    amount_paid numeric(10,2) NOT NULL DEFAULT 0,
    amount_owed numeric(10,2) NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text)
);

ALTER TABLE public."SpendingSplits"
    ADD CONSTRAINT "SpendingSplits_spending_id_fkey" FOREIGN KEY (spending_id) REFERENCES public."Spendings"(id) ON DELETE CASCADE,
    ADD CONSTRAINT "SpendingSplits_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."Users"(id) ON DELETE CASCADE,
    ADD CONSTRAINT uq_spending_splits_spending_user UNIQUE (spending_id, user_id);

CREATE INDEX idx_spending_splits_user_id ON public."SpendingSplits" USING btree (user_id);

-- Backfill: participants = current UserRooms members of the expense's room
-- (no historical membership snapshot exists, so this is the best available
-- source for legacy expenses). Even split across the current member count;
-- the payer's row carries the full amount_paid, everyone else's is 0.
INSERT INTO public."SpendingSplits" (spending_id, user_id, amount_paid, amount_owed, created_at)
SELECT
    s.id,
    ur.user_id,
    CASE WHEN ur.user_id = s.user_id THEN s.money ELSE 0 END,
    ROUND(s.money / pc.participant_count, 2),
    s.created_at
FROM public."Spendings" s
JOIN public."UserRooms" ur ON ur.room_id = s.room
JOIN (
    SELECT room_id, COUNT(*) AS participant_count
    FROM public."UserRooms"
    GROUP BY room_id
) pc ON pc.room_id = s.room
WHERE pc.participant_count > 0;

-- New domain: one active row (settled_at IS NULL) per (room, user) plus
-- historical closed rows from past full settlements. Replaces `balance`.

CREATE TABLE public."RoomBalanceSummary" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id bigint NOT NULL,
    user_id bigint NOT NULL,
    pending_amount numeric(10,2) NOT NULL DEFAULT 0,
    settled_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text)
);

ALTER TABLE public."RoomBalanceSummary"
    ADD CONSTRAINT "RoomBalanceSummary_room_id_fkey" FOREIGN KEY (room_id) REFERENCES public."Rooms"(id) ON DELETE CASCADE,
    ADD CONSTRAINT "RoomBalanceSummary_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."Users"(id) ON DELETE CASCADE;

CREATE UNIQUE INDEX uq_room_balance_summary_active ON public."RoomBalanceSummary" (room_id, user_id) WHERE settled_at IS NULL;

-- Backfill: one active row per current UserRooms membership. pending_amount
-- is the net (amount_paid - amount_owed) across that member's unsettled
-- SpendingSplits rows in the room; members with no unsettled expenses still
-- get a row at pending_amount = 0.
INSERT INTO public."RoomBalanceSummary" (room_id, user_id, pending_amount, settled_at, updated_at)
SELECT
    ur.room_id,
    ur.user_id,
    COALESCE(net.pending_amount, 0),
    NULL,
    now()
FROM public."UserRooms" ur
LEFT JOIN (
    SELECT s.room AS room_id, ss.user_id, SUM(ss.amount_paid - ss.amount_owed) AS pending_amount
    FROM public."SpendingSplits" ss
    JOIN public."Spendings" s ON s.id = ss.spending_id
    WHERE s.settled_at IS NULL AND s.settled = false
    GROUP BY s.room, ss.user_id
) net ON net.room_id = ur.room_id AND net.user_id = ur.user_id;

-- migrate:down

DROP TABLE public."RoomBalanceSummary";
DROP TABLE public."SpendingSplits";
