[project]
name = "RoomGrub-backend"
version = "0.0.1"
description = "Expense splitter app for friends and family groups"
authors = [
  {name = "Sankar Swain", email = "s.sankar@broccly.in"}
]
readme = "README.md"
dependencies = [
    "fastapi >= 0.138.0",
    "uvicorn[standard] >= 0.49.0",
    "pydantic >= 2.13.4",
    "alembic >= 1.18.5",
    "PyJWT >= 2.8",
    "sqlalchemy >= 2.0",
    "psycopg2-binary >= 2.9",
    "python-dotenv >= 1.0",
    "httpx >= 0.27",
    "redis >= 5.0",
    "google-auth >= 2.34.0",
    "requests >= 2.32.0",
    "firebase_admin >= 7.6.0"
]